// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_enum_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EnumHolderCodec;
  try {
    final data = File('$vec/EnumHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EnumHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EnumHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EnumHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EnumHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_enum_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptEnumHolderCodec;
  try {
    final data = File('$vec/OptEnumHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptEnumHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptEnumHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptEnumHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptEnumHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptEnumHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptEnumHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptEnumHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptEnumHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptEnumHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptEnumHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptEnumHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_enum_array_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EnumArrayHolderCodec;
  try {
    final data = File('$vec/EnumArrayHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EnumArrayHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumArrayHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumArrayHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EnumArrayHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumArrayHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumArrayHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EnumArrayHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumArrayHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumArrayHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EnumArrayHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumArrayHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_enum_mixed_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EnumMixedHolderCodec;
  try {
    final data = File('$vec/EnumMixedHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EnumMixedHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumMixedHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumMixedHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EnumMixedHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumMixedHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumMixedHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EnumMixedHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumMixedHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EnumMixedHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EnumMixedHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EnumMixedHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesEnums(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (penum_holder, fenum_holder) = testModel_enum_holder(vec, out); passed += penum_holder; failed += fenum_holder;
  final (popt_enum_holder, fopt_enum_holder) = testModel_opt_enum_holder(vec, out); passed += popt_enum_holder; failed += fopt_enum_holder;
  final (penum_array_holder, fenum_array_holder) = testModel_enum_array_holder(vec, out); passed += penum_array_holder; failed += fenum_array_holder;
  final (penum_mixed_holder, fenum_mixed_holder) = testModel_enum_mixed_holder(vec, out); passed += penum_mixed_holder; failed += fenum_mixed_holder;
  return (passed, failed);
}
