// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_model_arr1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ModelArr1Codec;
  try {
    final data = File('$vec/ModelArr1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ModelArr1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ModelArr1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_model_arr2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ModelArr2Codec;
  try {
    final data = File('$vec/ModelArr2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ModelArr2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ModelArr2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_model_arr3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ModelArr3Codec;
  try {
    final data = File('$vec/ModelArr3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ModelArr3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ModelArr3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_model_arr4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ModelArr4Codec;
  try {
    final data = File('$vec/ModelArr4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ModelArr4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ModelArr4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_model_arr5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ModelArr5Codec;
  try {
    final data = File('$vec/ModelArr5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ModelArr5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ModelArr5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ModelArr5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ModelArr5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ModelArr5 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix01(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix01Codec;
  try {
    final data = File('$vec/Mix01.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix01.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix01 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix01.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix01.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix01 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix01.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix01.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix01 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix01.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix01.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix01 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix02(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix02Codec;
  try {
    final data = File('$vec/Mix02.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix02.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix02 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix02.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix02.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix02 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix02.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix02.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix02 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix02.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix02.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix02 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix03(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix03Codec;
  try {
    final data = File('$vec/Mix03.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix03.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix03 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix03.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix03.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix03 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix03.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix03.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix03 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix03.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix03.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix03 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix04(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix04Codec;
  try {
    final data = File('$vec/Mix04.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix04.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix04 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix04.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix04.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix04 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix04.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix04.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix04 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix04.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix04.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix04 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix05(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix05Codec;
  try {
    final data = File('$vec/Mix05.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix05.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix05 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix05.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix05.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix05 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix05.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix05.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix05 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix05.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix05.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix05 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix06(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix06Codec;
  try {
    final data = File('$vec/Mix06.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix06.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix06 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix06.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix06.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix06 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix06.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix06.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix06 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix06.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix06.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix06 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix07(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix07Codec;
  try {
    final data = File('$vec/Mix07.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix07.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix07 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix07.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix07.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix07 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix07.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix07.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix07 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix07.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix07.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix07 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix08(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix08Codec;
  try {
    final data = File('$vec/Mix08.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix08.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix08 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix08.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix08.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix08 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix08.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix08.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix08 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix08.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix08.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix08 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix09(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix09Codec;
  try {
    final data = File('$vec/Mix09.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix09.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix09 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix09.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix09.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix09 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix09.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix09.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix09 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix09.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix09.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix09 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix10(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix10Codec;
  try {
    final data = File('$vec/Mix10.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix10.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix10 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix10.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix10.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix10 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix10.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix10.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix10 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix10.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix10.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix10 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix11(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix11Codec;
  try {
    final data = File('$vec/Mix11.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix11.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix11 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix11.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix11.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix11 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix11.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix11.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix11 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix11.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix11.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix11 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix12(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix12Codec;
  try {
    final data = File('$vec/Mix12.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix12.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix12 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix12.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix12.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix12 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix12.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix12.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix12 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix12.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix12.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix12 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix13(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix13Codec;
  try {
    final data = File('$vec/Mix13.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix13.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix13 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix13.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix13.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix13 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix13.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix13.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix13 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix13.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix13.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix13 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix14(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix14Codec;
  try {
    final data = File('$vec/Mix14.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix14.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix14 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix14.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix14.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix14 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix14.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix14.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix14 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix14.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix14.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix14 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mix15(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Mix15Codec;
  try {
    final data = File('$vec/Mix15.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Mix15.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix15 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix15.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix15.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix15 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix15.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Mix15.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix15 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Mix15.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Mix15.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Mix15 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_all_opt1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = AllOpt1Codec;
  try {
    final data = File('$vec/AllOpt1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/AllOpt1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/AllOpt1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_all_opt2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = AllOpt2Codec;
  try {
    final data = File('$vec/AllOpt2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/AllOpt2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/AllOpt2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_all_opt3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = AllOpt3Codec;
  try {
    final data = File('$vec/AllOpt3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/AllOpt3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/AllOpt3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_all_opt4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = AllOpt4Codec;
  try {
    final data = File('$vec/AllOpt4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/AllOpt4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/AllOpt4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_all_opt5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = AllOpt5Codec;
  try {
    final data = File('$vec/AllOpt5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/AllOpt5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/AllOpt5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/AllOpt5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/AllOpt5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL AllOpt5 gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesMixed(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pmodel_arr1, fmodel_arr1) = testModel_model_arr1(vec, out); passed += pmodel_arr1; failed += fmodel_arr1;
  final (pmodel_arr2, fmodel_arr2) = testModel_model_arr2(vec, out); passed += pmodel_arr2; failed += fmodel_arr2;
  final (pmodel_arr3, fmodel_arr3) = testModel_model_arr3(vec, out); passed += pmodel_arr3; failed += fmodel_arr3;
  final (pmodel_arr4, fmodel_arr4) = testModel_model_arr4(vec, out); passed += pmodel_arr4; failed += fmodel_arr4;
  final (pmodel_arr5, fmodel_arr5) = testModel_model_arr5(vec, out); passed += pmodel_arr5; failed += fmodel_arr5;
  final (pmix01, fmix01) = testModel_mix01(vec, out); passed += pmix01; failed += fmix01;
  final (pmix02, fmix02) = testModel_mix02(vec, out); passed += pmix02; failed += fmix02;
  final (pmix03, fmix03) = testModel_mix03(vec, out); passed += pmix03; failed += fmix03;
  final (pmix04, fmix04) = testModel_mix04(vec, out); passed += pmix04; failed += fmix04;
  final (pmix05, fmix05) = testModel_mix05(vec, out); passed += pmix05; failed += fmix05;
  final (pmix06, fmix06) = testModel_mix06(vec, out); passed += pmix06; failed += fmix06;
  final (pmix07, fmix07) = testModel_mix07(vec, out); passed += pmix07; failed += fmix07;
  final (pmix08, fmix08) = testModel_mix08(vec, out); passed += pmix08; failed += fmix08;
  final (pmix09, fmix09) = testModel_mix09(vec, out); passed += pmix09; failed += fmix09;
  final (pmix10, fmix10) = testModel_mix10(vec, out); passed += pmix10; failed += fmix10;
  final (pmix11, fmix11) = testModel_mix11(vec, out); passed += pmix11; failed += fmix11;
  final (pmix12, fmix12) = testModel_mix12(vec, out); passed += pmix12; failed += fmix12;
  final (pmix13, fmix13) = testModel_mix13(vec, out); passed += pmix13; failed += fmix13;
  final (pmix14, fmix14) = testModel_mix14(vec, out); passed += pmix14; failed += fmix14;
  final (pmix15, fmix15) = testModel_mix15(vec, out); passed += pmix15; failed += fmix15;
  final (pall_opt1, fall_opt1) = testModel_all_opt1(vec, out); passed += pall_opt1; failed += fall_opt1;
  final (pall_opt2, fall_opt2) = testModel_all_opt2(vec, out); passed += pall_opt2; failed += fall_opt2;
  final (pall_opt3, fall_opt3) = testModel_all_opt3(vec, out); passed += pall_opt3; failed += fall_opt3;
  final (pall_opt4, fall_opt4) = testModel_all_opt4(vec, out); passed += pall_opt4; failed += fall_opt4;
  final (pall_opt5, fall_opt5) = testModel_all_opt5(vec, out); passed += pall_opt5; failed += fall_opt5;
  return (passed, failed);
}
