// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_union_field_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = UnionFieldHolderCodec;
  try {
    final data = File('$vec/UnionFieldHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/UnionFieldHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionFieldHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionFieldHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionFieldHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionFieldHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionFieldHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionFieldHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionFieldHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionFieldHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/UnionFieldHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionFieldHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_union_field_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptUnionFieldHolderCodec;
  try {
    final data = File('$vec/OptUnionFieldHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptUnionFieldHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionFieldHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionFieldHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptUnionFieldHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionFieldHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionFieldHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptUnionFieldHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionFieldHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionFieldHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptUnionFieldHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionFieldHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_union_array_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = UnionArrayHolderCodec;
  try {
    final data = File('$vec/UnionArrayHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/UnionArrayHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionArrayHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionArrayHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionArrayHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionArrayHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionArrayHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionArrayHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionArrayHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionArrayHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/UnionArrayHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionArrayHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_union_mixed_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = UnionMixedHolderCodec;
  try {
    final data = File('$vec/UnionMixedHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/UnionMixedHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionMixedHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionMixedHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionMixedHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionMixedHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionMixedHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionMixedHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionMixedHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionMixedHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/UnionMixedHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionMixedHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_union_scalar_holder(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = UnionScalarHolderCodec;
  try {
    final data = File('$vec/UnionScalarHolder.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/UnionScalarHolder.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionScalarHolder mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionScalarHolder.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionScalarHolder.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionScalarHolder json: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionScalarHolder.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/UnionScalarHolder.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionScalarHolder unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/UnionScalarHolder.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/UnionScalarHolder.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL UnionScalarHolder gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesUnions(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (punion_field_holder, funion_field_holder) = testModel_union_field_holder(vec, out); passed += punion_field_holder; failed += funion_field_holder;
  final (popt_union_field_holder, fopt_union_field_holder) = testModel_opt_union_field_holder(vec, out); passed += popt_union_field_holder; failed += fopt_union_field_holder;
  final (punion_array_holder, funion_array_holder) = testModel_union_array_holder(vec, out); passed += punion_array_holder; failed += funion_array_holder;
  final (punion_mixed_holder, funion_mixed_holder) = testModel_union_mixed_holder(vec, out); passed += punion_mixed_holder; failed += funion_mixed_holder;
  final (punion_scalar_holder, funion_scalar_holder) = testModel_union_scalar_holder(vec, out); passed += punion_scalar_holder; failed += funion_scalar_holder;
  return (passed, failed);
}
