// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_wide20(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Wide20Codec;
  try {
    final data = File('$vec/Wide20.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Wide20.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide20 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide20.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide20.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide20 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide20.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide20.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide20 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide20.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Wide20.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide20 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_wide25(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Wide25Codec;
  try {
    final data = File('$vec/Wide25.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Wide25.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide25 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide25.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide25.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide25 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide25.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide25.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide25 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide25.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Wide25.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide25 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_wide30(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Wide30Codec;
  try {
    final data = File('$vec/Wide30.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Wide30.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide30 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide30.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide30.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide30 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide30.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide30.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide30 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide30.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Wide30.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide30 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_wide35(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Wide35Codec;
  try {
    final data = File('$vec/Wide35.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Wide35.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide35 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide35.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide35.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide35 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide35.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide35.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide35 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide35.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Wide35.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide35 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_wide40(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Wide40Codec;
  try {
    final data = File('$vec/Wide40.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Wide40.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide40 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide40.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide40.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide40 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide40.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Wide40.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide40 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Wide40.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Wide40.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Wide40 gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesWide(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pwide20, fwide20) = testModel_wide20(vec, out); passed += pwide20; failed += fwide20;
  final (pwide25, fwide25) = testModel_wide25(vec, out); passed += pwide25; failed += fwide25;
  final (pwide30, fwide30) = testModel_wide30(vec, out); passed += pwide30; failed += fwide30;
  final (pwide35, fwide35) = testModel_wide35(vec, out); passed += pwide35; failed += fwide35;
  final (pwide40, fwide40) = testModel_wide40(vec, out); passed += pwide40; failed += fwide40;
  return (passed, failed);
}
