// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_pair_string(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairStringCodec;
  try {
    final data = File('$vec/PairString.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairString.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairString mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairString.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairString.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairString json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairString.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairString.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairString unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairString.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairString.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairString gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairBooleanCodec;
  try {
    final data = File('$vec/PairBoolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairBoolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBoolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairBoolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairBoolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBoolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairBoolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairBoolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBoolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairBoolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairBoolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBoolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_int8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairInt8Codec;
  try {
    final data = File('$vec/PairInt8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairInt8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairInt8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_int16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairInt16Codec;
  try {
    final data = File('$vec/PairInt16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairInt16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairInt16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairInt32Codec;
  try {
    final data = File('$vec/PairInt32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairInt32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairInt32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairInt64Codec;
  try {
    final data = File('$vec/PairInt64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairInt64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairInt64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairInt64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairInt64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairInt64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_uint8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairUint8Codec;
  try {
    final data = File('$vec/PairUint8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairUint8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairUint8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_uint16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairUint16Codec;
  try {
    final data = File('$vec/PairUint16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairUint16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairUint16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_uint32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairUint32Codec;
  try {
    final data = File('$vec/PairUint32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairUint32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairUint32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairUint64Codec;
  try {
    final data = File('$vec/PairUint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairUint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairUint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairUint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairUint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairUint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_float32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairFloat32Codec;
  try {
    final data = File('$vec/PairFloat32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairFloat32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairFloat32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairFloat32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairFloat32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairFloat32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairFloat32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairFloat32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairFloat64Codec;
  try {
    final data = File('$vec/PairFloat64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairFloat64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairFloat64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairFloat64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairFloat64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairFloat64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairFloat64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairFloat64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairFloat64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_pair_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = PairBytesCodec;
  try {
    final data = File('$vec/PairBytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/PairBytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairBytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairBytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairBytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/PairBytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/PairBytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/PairBytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL PairBytes gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_string_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualStringInt32Codec;
  try {
    final data = File('$vec/DualStringInt32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringInt32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringInt32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringInt32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_string_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualStringBooleanCodec;
  try {
    final data = File('$vec/DualStringBoolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualStringBoolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBoolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringBoolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringBoolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBoolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringBoolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringBoolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBoolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringBoolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualStringBoolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBoolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_string_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualStringFloat64Codec;
  try {
    final data = File('$vec/DualStringFloat64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualStringFloat64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringFloat64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringFloat64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringFloat64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringFloat64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringFloat64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringFloat64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringFloat64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringFloat64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualStringFloat64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringFloat64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_string_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualStringBytesCodec;
  try {
    final data = File('$vec/DualStringBytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualStringBytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringBytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringBytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringBytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringBytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringBytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualStringBytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringBytes gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int32_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt32BooleanCodec;
  try {
    final data = File('$vec/DualInt32Boolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Boolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Boolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Boolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Boolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Boolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Boolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Boolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Boolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Boolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Boolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Boolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int32_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt32Float64Codec;
  try {
    final data = File('$vec/DualInt32Float64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Float64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Float64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Float64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Float64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Float64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Float64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Float64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Float64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Float64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Float64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Float64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int32_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt32Int64Codec;
  try {
    final data = File('$vec/DualInt32Int64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Int64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Int64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Int64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Int64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Int64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Int64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Int64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Int64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Int64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Int64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Int64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int32_uint32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt32Uint32Codec;
  try {
    final data = File('$vec/DualInt32Uint32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Uint32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Uint32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Uint32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Uint32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Uint32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Uint32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Uint32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Uint32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Uint32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Uint32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Uint32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int64_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt64Uint64Codec;
  try {
    final data = File('$vec/DualInt64Uint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Uint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Uint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt64Uint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Uint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Uint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt64Uint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Uint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Uint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt64Uint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Uint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Uint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_float32_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualFloat32Float64Codec;
  try {
    final data = File('$vec/DualFloat32Float64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualFloat32Float64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat32Float64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat32Float64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat32Float64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat32Float64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat32Float64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat32Float64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat32Float64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat32Float64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualFloat32Float64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat32Float64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_float64_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualFloat64BooleanCodec;
  try {
    final data = File('$vec/DualFloat64Boolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Boolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Boolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Boolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Boolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Boolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Boolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Boolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Boolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Boolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Boolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Boolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_float64_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualFloat64BytesCodec;
  try {
    final data = File('$vec/DualFloat64Bytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Bytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Bytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Bytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Bytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Bytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Bytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Bytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Bytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Bytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Bytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Bytes gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_uint32_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualUint32Uint64Codec;
  try {
    final data = File('$vec/DualUint32Uint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualUint32Uint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint32Uint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint32Uint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualUint32Uint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint32Uint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint32Uint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualUint32Uint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint32Uint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint32Uint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualUint32Uint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint32Uint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_boolean_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualBooleanBytesCodec;
  try {
    final data = File('$vec/DualBooleanBytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanBytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanBytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBooleanBytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanBytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanBytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBooleanBytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanBytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanBytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBooleanBytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanBytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanBytes gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int8_uint8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt8Uint8Codec;
  try {
    final data = File('$vec/DualInt8Uint8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Uint8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Uint8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt8Uint8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Uint8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Uint8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt8Uint8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Uint8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Uint8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt8Uint8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Uint8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Uint8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int16_uint16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt16Uint16Codec;
  try {
    final data = File('$vec/DualInt16Uint16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt16Uint16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt16Uint16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt16Uint16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt16Uint16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt16Uint16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt16Uint16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt16Uint16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt16Uint16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt16Uint16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt16Uint16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt16Uint16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_string_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualStringInt64Codec;
  try {
    final data = File('$vec/DualStringInt64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringInt64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringInt64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringInt64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualStringInt64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringInt64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_string_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualStringUint64Codec;
  try {
    final data = File('$vec/DualStringUint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualStringUint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringUint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringUint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringUint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringUint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringUint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualStringUint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringUint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualStringUint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualStringUint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualStringUint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int32_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt32BytesCodec;
  try {
    final data = File('$vec/DualInt32Bytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Bytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Bytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Bytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Bytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Bytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Bytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Bytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Bytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt32Bytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt32Bytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt32Bytes gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_float64_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualFloat64Int32Codec;
  try {
    final data = File('$vec/DualFloat64Int32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Int32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Int32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Int32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Int32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Int32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Int32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Int32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Int32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualFloat64Int32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualFloat64Int32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualFloat64Int32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_boolean_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualBooleanInt32Codec;
  try {
    final data = File('$vec/DualBooleanInt32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanInt32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanInt32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBooleanInt32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanInt32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanInt32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBooleanInt32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanInt32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanInt32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBooleanInt32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualBooleanInt32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBooleanInt32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_bytes_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualBytesInt64Codec;
  try {
    final data = File('$vec/DualBytesInt64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualBytesInt64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBytesInt64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBytesInt64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualBytesInt64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBytesInt64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBytesInt64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualBytesInt64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBytesInt64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualBytesInt64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualBytesInt64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualBytesInt64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int8_float32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt8Float32Codec;
  try {
    final data = File('$vec/DualInt8Float32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Float32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Float32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt8Float32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Float32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Float32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt8Float32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Float32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Float32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt8Float32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt8Float32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt8Float32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_uint8_int16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualUint8Int16Codec;
  try {
    final data = File('$vec/DualUint8Int16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualUint8Int16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint8Int16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint8Int16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualUint8Int16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint8Int16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint8Int16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualUint8Int16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint8Int16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint8Int16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualUint8Int16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint8Int16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_int64_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualInt64Float64Codec;
  try {
    final data = File('$vec/DualInt64Float64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Float64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Float64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt64Float64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Float64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Float64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt64Float64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Float64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Float64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualInt64Float64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualInt64Float64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualInt64Float64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_dual_uint64_string(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DualUint64StringCodec;
  try {
    final data = File('$vec/DualUint64String.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DualUint64String.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint64String mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint64String.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualUint64String.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint64String json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint64String.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DualUint64String.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint64String unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DualUint64String.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DualUint64String.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DualUint64String gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple01(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple01Codec;
  try {
    final data = File('$vec/Triple01.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple01.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple01 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple01.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple01.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple01 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple01.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple01.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple01 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple01.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple01.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple01 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple02(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple02Codec;
  try {
    final data = File('$vec/Triple02.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple02.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple02 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple02.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple02.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple02 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple02.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple02.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple02 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple02.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple02.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple02 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple03(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple03Codec;
  try {
    final data = File('$vec/Triple03.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple03.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple03 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple03.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple03.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple03 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple03.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple03.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple03 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple03.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple03.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple03 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple04(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple04Codec;
  try {
    final data = File('$vec/Triple04.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple04.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple04 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple04.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple04.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple04 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple04.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple04.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple04 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple04.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple04.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple04 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple05(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple05Codec;
  try {
    final data = File('$vec/Triple05.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple05.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple05 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple05.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple05.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple05 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple05.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple05.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple05 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple05.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple05.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple05 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple06(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple06Codec;
  try {
    final data = File('$vec/Triple06.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple06.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple06 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple06.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple06.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple06 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple06.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple06.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple06 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple06.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple06.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple06 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple07(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple07Codec;
  try {
    final data = File('$vec/Triple07.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple07.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple07 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple07.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple07.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple07 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple07.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple07.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple07 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple07.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple07.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple07 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple08(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple08Codec;
  try {
    final data = File('$vec/Triple08.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple08.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple08 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple08.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple08.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple08 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple08.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple08.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple08 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple08.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple08.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple08 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple09(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple09Codec;
  try {
    final data = File('$vec/Triple09.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple09.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple09 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple09.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple09.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple09 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple09.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple09.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple09 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple09.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple09.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple09 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple10(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple10Codec;
  try {
    final data = File('$vec/Triple10.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple10.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple10 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple10.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple10.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple10 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple10.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple10.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple10 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple10.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple10.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple10 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple11(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple11Codec;
  try {
    final data = File('$vec/Triple11.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple11.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple11 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple11.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple11.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple11 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple11.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple11.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple11 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple11.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple11.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple11 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple12(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple12Codec;
  try {
    final data = File('$vec/Triple12.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple12.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple12 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple12.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple12.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple12 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple12.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple12.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple12 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple12.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple12.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple12 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple13(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple13Codec;
  try {
    final data = File('$vec/Triple13.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple13.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple13 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple13.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple13.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple13 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple13.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple13.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple13 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple13.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple13.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple13 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple14(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple14Codec;
  try {
    final data = File('$vec/Triple14.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple14.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple14 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple14.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple14.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple14 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple14.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple14.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple14 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple14.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple14.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple14 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_triple15(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Triple15Codec;
  try {
    final data = File('$vec/Triple15.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Triple15.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple15 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple15.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple15.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple15 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple15.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Triple15.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple15 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Triple15.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Triple15.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Triple15 gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesPairs(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (ppair_string, fpair_string) = testModel_pair_string(vec, out); passed += ppair_string; failed += fpair_string;
  final (ppair_boolean, fpair_boolean) = testModel_pair_boolean(vec, out); passed += ppair_boolean; failed += fpair_boolean;
  final (ppair_int8, fpair_int8) = testModel_pair_int8(vec, out); passed += ppair_int8; failed += fpair_int8;
  final (ppair_int16, fpair_int16) = testModel_pair_int16(vec, out); passed += ppair_int16; failed += fpair_int16;
  final (ppair_int32, fpair_int32) = testModel_pair_int32(vec, out); passed += ppair_int32; failed += fpair_int32;
  final (ppair_int64, fpair_int64) = testModel_pair_int64(vec, out); passed += ppair_int64; failed += fpair_int64;
  final (ppair_uint8, fpair_uint8) = testModel_pair_uint8(vec, out); passed += ppair_uint8; failed += fpair_uint8;
  final (ppair_uint16, fpair_uint16) = testModel_pair_uint16(vec, out); passed += ppair_uint16; failed += fpair_uint16;
  final (ppair_uint32, fpair_uint32) = testModel_pair_uint32(vec, out); passed += ppair_uint32; failed += fpair_uint32;
  final (ppair_uint64, fpair_uint64) = testModel_pair_uint64(vec, out); passed += ppair_uint64; failed += fpair_uint64;
  final (ppair_float32, fpair_float32) = testModel_pair_float32(vec, out); passed += ppair_float32; failed += fpair_float32;
  final (ppair_float64, fpair_float64) = testModel_pair_float64(vec, out); passed += ppair_float64; failed += fpair_float64;
  final (ppair_bytes, fpair_bytes) = testModel_pair_bytes(vec, out); passed += ppair_bytes; failed += fpair_bytes;
  final (pdual_string_int32, fdual_string_int32) = testModel_dual_string_int32(vec, out); passed += pdual_string_int32; failed += fdual_string_int32;
  final (pdual_string_boolean, fdual_string_boolean) = testModel_dual_string_boolean(vec, out); passed += pdual_string_boolean; failed += fdual_string_boolean;
  final (pdual_string_float64, fdual_string_float64) = testModel_dual_string_float64(vec, out); passed += pdual_string_float64; failed += fdual_string_float64;
  final (pdual_string_bytes, fdual_string_bytes) = testModel_dual_string_bytes(vec, out); passed += pdual_string_bytes; failed += fdual_string_bytes;
  final (pdual_int32_boolean, fdual_int32_boolean) = testModel_dual_int32_boolean(vec, out); passed += pdual_int32_boolean; failed += fdual_int32_boolean;
  final (pdual_int32_float64, fdual_int32_float64) = testModel_dual_int32_float64(vec, out); passed += pdual_int32_float64; failed += fdual_int32_float64;
  final (pdual_int32_int64, fdual_int32_int64) = testModel_dual_int32_int64(vec, out); passed += pdual_int32_int64; failed += fdual_int32_int64;
  final (pdual_int32_uint32, fdual_int32_uint32) = testModel_dual_int32_uint32(vec, out); passed += pdual_int32_uint32; failed += fdual_int32_uint32;
  final (pdual_int64_uint64, fdual_int64_uint64) = testModel_dual_int64_uint64(vec, out); passed += pdual_int64_uint64; failed += fdual_int64_uint64;
  final (pdual_float32_float64, fdual_float32_float64) = testModel_dual_float32_float64(vec, out); passed += pdual_float32_float64; failed += fdual_float32_float64;
  final (pdual_float64_boolean, fdual_float64_boolean) = testModel_dual_float64_boolean(vec, out); passed += pdual_float64_boolean; failed += fdual_float64_boolean;
  final (pdual_float64_bytes, fdual_float64_bytes) = testModel_dual_float64_bytes(vec, out); passed += pdual_float64_bytes; failed += fdual_float64_bytes;
  final (pdual_uint32_uint64, fdual_uint32_uint64) = testModel_dual_uint32_uint64(vec, out); passed += pdual_uint32_uint64; failed += fdual_uint32_uint64;
  final (pdual_boolean_bytes, fdual_boolean_bytes) = testModel_dual_boolean_bytes(vec, out); passed += pdual_boolean_bytes; failed += fdual_boolean_bytes;
  final (pdual_int8_uint8, fdual_int8_uint8) = testModel_dual_int8_uint8(vec, out); passed += pdual_int8_uint8; failed += fdual_int8_uint8;
  final (pdual_int16_uint16, fdual_int16_uint16) = testModel_dual_int16_uint16(vec, out); passed += pdual_int16_uint16; failed += fdual_int16_uint16;
  final (pdual_string_int64, fdual_string_int64) = testModel_dual_string_int64(vec, out); passed += pdual_string_int64; failed += fdual_string_int64;
  final (pdual_string_uint64, fdual_string_uint64) = testModel_dual_string_uint64(vec, out); passed += pdual_string_uint64; failed += fdual_string_uint64;
  final (pdual_int32_bytes, fdual_int32_bytes) = testModel_dual_int32_bytes(vec, out); passed += pdual_int32_bytes; failed += fdual_int32_bytes;
  final (pdual_float64_int32, fdual_float64_int32) = testModel_dual_float64_int32(vec, out); passed += pdual_float64_int32; failed += fdual_float64_int32;
  final (pdual_boolean_int32, fdual_boolean_int32) = testModel_dual_boolean_int32(vec, out); passed += pdual_boolean_int32; failed += fdual_boolean_int32;
  final (pdual_bytes_int64, fdual_bytes_int64) = testModel_dual_bytes_int64(vec, out); passed += pdual_bytes_int64; failed += fdual_bytes_int64;
  final (pdual_int8_float32, fdual_int8_float32) = testModel_dual_int8_float32(vec, out); passed += pdual_int8_float32; failed += fdual_int8_float32;
  final (pdual_uint8_int16, fdual_uint8_int16) = testModel_dual_uint8_int16(vec, out); passed += pdual_uint8_int16; failed += fdual_uint8_int16;
  final (pdual_int64_float64, fdual_int64_float64) = testModel_dual_int64_float64(vec, out); passed += pdual_int64_float64; failed += fdual_int64_float64;
  final (pdual_uint64_string, fdual_uint64_string) = testModel_dual_uint64_string(vec, out); passed += pdual_uint64_string; failed += fdual_uint64_string;
  final (ptriple01, ftriple01) = testModel_triple01(vec, out); passed += ptriple01; failed += ftriple01;
  final (ptriple02, ftriple02) = testModel_triple02(vec, out); passed += ptriple02; failed += ftriple02;
  final (ptriple03, ftriple03) = testModel_triple03(vec, out); passed += ptriple03; failed += ftriple03;
  final (ptriple04, ftriple04) = testModel_triple04(vec, out); passed += ptriple04; failed += ftriple04;
  final (ptriple05, ftriple05) = testModel_triple05(vec, out); passed += ptriple05; failed += ftriple05;
  final (ptriple06, ftriple06) = testModel_triple06(vec, out); passed += ptriple06; failed += ftriple06;
  final (ptriple07, ftriple07) = testModel_triple07(vec, out); passed += ptriple07; failed += ftriple07;
  final (ptriple08, ftriple08) = testModel_triple08(vec, out); passed += ptriple08; failed += ftriple08;
  final (ptriple09, ftriple09) = testModel_triple09(vec, out); passed += ptriple09; failed += ftriple09;
  final (ptriple10, ftriple10) = testModel_triple10(vec, out); passed += ptriple10; failed += ftriple10;
  final (ptriple11, ftriple11) = testModel_triple11(vec, out); passed += ptriple11; failed += ftriple11;
  final (ptriple12, ftriple12) = testModel_triple12(vec, out); passed += ptriple12; failed += ftriple12;
  final (ptriple13, ftriple13) = testModel_triple13(vec, out); passed += ptriple13; failed += ftriple13;
  final (ptriple14, ftriple14) = testModel_triple14(vec, out); passed += ptriple14; failed += ftriple14;
  final (ptriple15, ftriple15) = testModel_triple15(vec, out); passed += ptriple15; failed += ftriple15;
  return (passed, failed);
}
