// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_deep_model(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepModelCodec;
  try {
    final data = File('$vec/DeepModel.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepModel.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepModel mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepModel.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepModel.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepModel json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepModel.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepModel.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepModel unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepModel.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepModel.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepModel gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesNestedDeep(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pdeep_model, fdeep_model) = testModel_deep_model(vec, out); passed += pdeep_model; failed += fdeep_model;
  return (passed, failed);
}
