// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_opt_inner(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptInnerCodec;
  try {
    final data = File('$vec/OptInner.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptInner.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptInner mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptInner.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptInner.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptInner json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptInner.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptInner.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptInner unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptInner.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptInner.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptInner gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypes(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (popt_inner, fopt_inner) = testModel_opt_inner(vec, out); passed += popt_inner; failed += fopt_inner;
  return (passed, failed);
}
