// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testScalar_int8_min(String vec, String out) {
  try {
    final data = File('$vec/scalars/int8_min.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt32();
    final w = MsgPackWriter();
    w.writeInt32(val);
    File('$out/scalars/int8_min.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int8_min mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int8_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/int8_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt32();
    final w = MsgPackWriter();
    w.writeInt32(val);
    File('$out/scalars/int8_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int8_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int16_min(String vec, String out) {
  try {
    final data = File('$vec/scalars/int16_min.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt32();
    final w = MsgPackWriter();
    w.writeInt32(val);
    File('$out/scalars/int16_min.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int16_min mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int16_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/int16_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt32();
    final w = MsgPackWriter();
    w.writeInt32(val);
    File('$out/scalars/int16_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int16_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int32_min(String vec, String out) {
  try {
    final data = File('$vec/scalars/int32_min.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt32();
    final w = MsgPackWriter();
    w.writeInt32(val);
    File('$out/scalars/int32_min.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int32_min mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int32_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/int32_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt32();
    final w = MsgPackWriter();
    w.writeInt32(val);
    File('$out/scalars/int32_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int32_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int64_min(String vec, String out) {
  try {
    final data = File('$vec/scalars/int64_min.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt64();
    final w = MsgPackWriter();
    w.writeInt64(val);
    File('$out/scalars/int64_min.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int64_min mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_int64_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/int64_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readInt64();
    final w = MsgPackWriter();
    w.writeInt64(val);
    File('$out/scalars/int64_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL int64_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_uint8_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/uint8_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readUint32();
    final w = MsgPackWriter();
    w.writeUint32(val);
    File('$out/scalars/uint8_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL uint8_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_uint16_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/uint16_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readUint32();
    final w = MsgPackWriter();
    w.writeUint32(val);
    File('$out/scalars/uint16_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL uint16_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_uint32_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/uint32_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readUint32();
    final w = MsgPackWriter();
    w.writeUint32(val);
    File('$out/scalars/uint32_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL uint32_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_uint64_max(String vec, String out) {
  try {
    final data = File('$vec/scalars/uint64_max.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readUint64();
    final w = MsgPackWriter();
    w.writeUint64(val);
    File('$out/scalars/uint64_max.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL uint64_max mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float32_1_5(String vec, String out) {
  try {
    final data = File('$vec/scalars/float32_1.5.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat32();
    final w = MsgPackWriter();
    w.writeFloat32(val);
    File('$out/scalars/float32_1.5.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float32_1.5 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float32_neg_zero(String vec, String out) {
  try {
    final data = File('$vec/scalars/float32_neg_zero.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat32();
    final w = MsgPackWriter();
    w.writeFloat32(val);
    File('$out/scalars/float32_neg_zero.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float32_neg_zero mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float32_inf(String vec, String out) {
  try {
    final data = File('$vec/scalars/float32_inf.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat32();
    final w = MsgPackWriter();
    w.writeFloat32(val);
    File('$out/scalars/float32_inf.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float32_inf mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float32_neg_inf(String vec, String out) {
  try {
    final data = File('$vec/scalars/float32_neg_inf.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat32();
    final w = MsgPackWriter();
    w.writeFloat32(val);
    File('$out/scalars/float32_neg_inf.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float32_neg_inf mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float32_nan(String vec, String out) {
  try {
    final data = File('$vec/scalars/float32_nan.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat32();
    final w = MsgPackWriter();
    w.writeFloat32(val);
    File('$out/scalars/float32_nan.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float32_nan mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float64_pi(String vec, String out) {
  try {
    final data = File('$vec/scalars/float64_pi.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat64();
    final w = MsgPackWriter();
    w.writeFloat64(val);
    File('$out/scalars/float64_pi.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float64_pi mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float64_neg_zero(String vec, String out) {
  try {
    final data = File('$vec/scalars/float64_neg_zero.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat64();
    final w = MsgPackWriter();
    w.writeFloat64(val);
    File('$out/scalars/float64_neg_zero.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float64_neg_zero mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float64_inf(String vec, String out) {
  try {
    final data = File('$vec/scalars/float64_inf.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat64();
    final w = MsgPackWriter();
    w.writeFloat64(val);
    File('$out/scalars/float64_inf.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float64_inf mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float64_neg_inf(String vec, String out) {
  try {
    final data = File('$vec/scalars/float64_neg_inf.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat64();
    final w = MsgPackWriter();
    w.writeFloat64(val);
    File('$out/scalars/float64_neg_inf.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float64_neg_inf mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_float64_nan(String vec, String out) {
  try {
    final data = File('$vec/scalars/float64_nan.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readFloat64();
    final w = MsgPackWriter();
    w.writeFloat64(val);
    File('$out/scalars/float64_nan.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL float64_nan mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_empty(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_empty.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_empty.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_empty mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_ascii(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_ascii.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_ascii.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_ascii mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_null_byte(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_null_byte.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_null_byte.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_null_byte mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_escape(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_escape.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_escape.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_escape mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_unicode(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_unicode.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_unicode.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_unicode mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_31(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_31.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_31.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_31 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_32(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_32.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_32.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_32 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_255(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_255.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_255.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_255 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_str_256(String vec, String out) {
  try {
    final data = File('$vec/scalars/str_256.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readString();
    final w = MsgPackWriter();
    w.writeString(val);
    File('$out/scalars/str_256.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL str_256 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_empty(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_empty.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_empty.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_empty mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_small(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_small.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_small.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_small mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_31(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_31.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_31.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_31 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_32(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_32.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_32.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_32 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_255(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_255.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_255.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_255 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_256(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_256.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_256.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_256 mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_zeros(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_zeros.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_zeros.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_zeros mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bytes_ff(String vec, String out) {
  try {
    final data = File('$vec/scalars/bytes_ff.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBytes();
    final w = MsgPackWriter();
    w.writeBytes(val);
    File('$out/scalars/bytes_ff.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bytes_ff mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bool_true(String vec, String out) {
  try {
    final data = File('$vec/scalars/bool_true.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBool();
    final w = MsgPackWriter();
    w.writeBool(val);
    File('$out/scalars/bool_true.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bool_true mp: $e');
    return (0, 1);
  }
}

(int, int) testScalar_bool_false(String vec, String out) {
  try {
    final data = File('$vec/scalars/bool_false.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.readBool();
    final w = MsgPackWriter();
    w.writeBool(val);
    File('$out/scalars/bool_false.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL bool_false mp: $e');
    return (0, 1);
  }
}
(int, int) runScalars(String vec, String out) {
  int passed = 0, failed = 0;

  // Scalar tests
  final (pint8_min, fint8_min) = testScalar_int8_min(vec, out); passed += pint8_min; failed += fint8_min;
  final (pint8_max, fint8_max) = testScalar_int8_max(vec, out); passed += pint8_max; failed += fint8_max;
  final (pint16_min, fint16_min) = testScalar_int16_min(vec, out); passed += pint16_min; failed += fint16_min;
  final (pint16_max, fint16_max) = testScalar_int16_max(vec, out); passed += pint16_max; failed += fint16_max;
  final (pint32_min, fint32_min) = testScalar_int32_min(vec, out); passed += pint32_min; failed += fint32_min;
  final (pint32_max, fint32_max) = testScalar_int32_max(vec, out); passed += pint32_max; failed += fint32_max;
  final (pint64_min, fint64_min) = testScalar_int64_min(vec, out); passed += pint64_min; failed += fint64_min;
  final (pint64_max, fint64_max) = testScalar_int64_max(vec, out); passed += pint64_max; failed += fint64_max;
  final (puint8_max, fuint8_max) = testScalar_uint8_max(vec, out); passed += puint8_max; failed += fuint8_max;
  final (puint16_max, fuint16_max) = testScalar_uint16_max(vec, out); passed += puint16_max; failed += fuint16_max;
  final (puint32_max, fuint32_max) = testScalar_uint32_max(vec, out); passed += puint32_max; failed += fuint32_max;
  final (puint64_max, fuint64_max) = testScalar_uint64_max(vec, out); passed += puint64_max; failed += fuint64_max;
  final (pfloat32_1_5, ffloat32_1_5) = testScalar_float32_1_5(vec, out); passed += pfloat32_1_5; failed += ffloat32_1_5;
  final (pfloat32_neg_zero, ffloat32_neg_zero) = testScalar_float32_neg_zero(vec, out); passed += pfloat32_neg_zero; failed += ffloat32_neg_zero;
  final (pfloat32_inf, ffloat32_inf) = testScalar_float32_inf(vec, out); passed += pfloat32_inf; failed += ffloat32_inf;
  final (pfloat32_neg_inf, ffloat32_neg_inf) = testScalar_float32_neg_inf(vec, out); passed += pfloat32_neg_inf; failed += ffloat32_neg_inf;
  final (pfloat32_nan, ffloat32_nan) = testScalar_float32_nan(vec, out); passed += pfloat32_nan; failed += ffloat32_nan;
  final (pfloat64_pi, ffloat64_pi) = testScalar_float64_pi(vec, out); passed += pfloat64_pi; failed += ffloat64_pi;
  final (pfloat64_neg_zero, ffloat64_neg_zero) = testScalar_float64_neg_zero(vec, out); passed += pfloat64_neg_zero; failed += ffloat64_neg_zero;
  final (pfloat64_inf, ffloat64_inf) = testScalar_float64_inf(vec, out); passed += pfloat64_inf; failed += ffloat64_inf;
  final (pfloat64_neg_inf, ffloat64_neg_inf) = testScalar_float64_neg_inf(vec, out); passed += pfloat64_neg_inf; failed += ffloat64_neg_inf;
  final (pfloat64_nan, ffloat64_nan) = testScalar_float64_nan(vec, out); passed += pfloat64_nan; failed += ffloat64_nan;
  final (pstr_empty, fstr_empty) = testScalar_str_empty(vec, out); passed += pstr_empty; failed += fstr_empty;
  final (pstr_ascii, fstr_ascii) = testScalar_str_ascii(vec, out); passed += pstr_ascii; failed += fstr_ascii;
  final (pstr_null_byte, fstr_null_byte) = testScalar_str_null_byte(vec, out); passed += pstr_null_byte; failed += fstr_null_byte;
  final (pstr_escape, fstr_escape) = testScalar_str_escape(vec, out); passed += pstr_escape; failed += fstr_escape;
  final (pstr_unicode, fstr_unicode) = testScalar_str_unicode(vec, out); passed += pstr_unicode; failed += fstr_unicode;
  final (pstr_31, fstr_31) = testScalar_str_31(vec, out); passed += pstr_31; failed += fstr_31;
  final (pstr_32, fstr_32) = testScalar_str_32(vec, out); passed += pstr_32; failed += fstr_32;
  final (pstr_255, fstr_255) = testScalar_str_255(vec, out); passed += pstr_255; failed += fstr_255;
  final (pstr_256, fstr_256) = testScalar_str_256(vec, out); passed += pstr_256; failed += fstr_256;
  final (pbytes_empty, fbytes_empty) = testScalar_bytes_empty(vec, out); passed += pbytes_empty; failed += fbytes_empty;
  final (pbytes_small, fbytes_small) = testScalar_bytes_small(vec, out); passed += pbytes_small; failed += fbytes_small;
  final (pbytes_31, fbytes_31) = testScalar_bytes_31(vec, out); passed += pbytes_31; failed += fbytes_31;
  final (pbytes_32, fbytes_32) = testScalar_bytes_32(vec, out); passed += pbytes_32; failed += fbytes_32;
  final (pbytes_255, fbytes_255) = testScalar_bytes_255(vec, out); passed += pbytes_255; failed += fbytes_255;
  final (pbytes_256, fbytes_256) = testScalar_bytes_256(vec, out); passed += pbytes_256; failed += fbytes_256;
  final (pbytes_zeros, fbytes_zeros) = testScalar_bytes_zeros(vec, out); passed += pbytes_zeros; failed += fbytes_zeros;
  final (pbytes_ff, fbytes_ff) = testScalar_bytes_ff(vec, out); passed += pbytes_ff; failed += fbytes_ff;
  final (pbool_true, fbool_true) = testScalar_bool_true(vec, out); passed += pbool_true; failed += fbool_true;
  final (pbool_false, fbool_false) = testScalar_bool_false(vec, out); passed += pbool_false; failed += fbool_false;
  return (passed, failed);
}
