// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_opt_arr1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptArr1Codec;
  try {
    final data = File('$vec/OptArr1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptArr1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptArr1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_arr2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptArr2Codec;
  try {
    final data = File('$vec/OptArr2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptArr2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptArr2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_arr3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptArr3Codec;
  try {
    final data = File('$vec/OptArr3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptArr3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptArr3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_arr4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptArr4Codec;
  try {
    final data = File('$vec/OptArr4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptArr4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptArr4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_arr5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptArr5Codec;
  try {
    final data = File('$vec/OptArr5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptArr5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptArr5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptArr5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptArr5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptArr5 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOpt1Codec;
  try {
    final data = File('$vec/NestOpt1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOpt1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOpt1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOpt2Codec;
  try {
    final data = File('$vec/NestOpt2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOpt2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOpt2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOpt3Codec;
  try {
    final data = File('$vec/NestOpt3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOpt3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOpt3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOpt4Codec;
  try {
    final data = File('$vec/NestOpt4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOpt4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOpt4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOpt5Codec;
  try {
    final data = File('$vec/NestOpt5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOpt5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOpt5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOpt5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOpt5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOpt5 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt_inner1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOptInner1Codec;
  try {
    final data = File('$vec/NestOptInner1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt_inner2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOptInner2Codec;
  try {
    final data = File('$vec/NestOptInner2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_opt_inner3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestOptInner3Codec;
  try {
    final data = File('$vec/NestOptInner3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestOptInner3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestOptInner3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestOptInner3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest1Codec;
  try {
    final data = File('$vec/DeepNest1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest2Codec;
  try {
    final data = File('$vec/DeepNest2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest3Codec;
  try {
    final data = File('$vec/DeepNest3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest4Codec;
  try {
    final data = File('$vec/DeepNest4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest5Codec;
  try {
    final data = File('$vec/DeepNest5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest5 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest6(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest6Codec;
  try {
    final data = File('$vec/DeepNest6.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest6.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest6 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest6.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest6.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest6 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest6.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest6.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest6 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest6.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest6.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest6 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_deep_nest7(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = DeepNest7Codec;
  try {
    final data = File('$vec/DeepNest7.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/DeepNest7.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest7 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest7.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest7.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest7 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest7.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/DeepNest7.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest7 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/DeepNest7.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/DeepNest7.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL DeepNest7 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_timestamp_entry(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = TimestampEntryCodec;
  try {
    final data = File('$vec/TimestampEntry.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/TimestampEntry.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL TimestampEntry mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/TimestampEntry.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/TimestampEntry.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL TimestampEntry json: $e');
    failed++;
  }
  try {
    final data = File('$vec/TimestampEntry.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/TimestampEntry.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL TimestampEntry unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/TimestampEntry.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/TimestampEntry.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL TimestampEntry gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_config_entry(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ConfigEntryCodec;
  try {
    final data = File('$vec/ConfigEntry.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ConfigEntry.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ConfigEntry mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ConfigEntry.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ConfigEntry.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ConfigEntry json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ConfigEntry.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ConfigEntry.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ConfigEntry unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ConfigEntry.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ConfigEntry.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ConfigEntry gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesExtra(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (popt_arr1, fopt_arr1) = testModel_opt_arr1(vec, out); passed += popt_arr1; failed += fopt_arr1;
  final (popt_arr2, fopt_arr2) = testModel_opt_arr2(vec, out); passed += popt_arr2; failed += fopt_arr2;
  final (popt_arr3, fopt_arr3) = testModel_opt_arr3(vec, out); passed += popt_arr3; failed += fopt_arr3;
  final (popt_arr4, fopt_arr4) = testModel_opt_arr4(vec, out); passed += popt_arr4; failed += fopt_arr4;
  final (popt_arr5, fopt_arr5) = testModel_opt_arr5(vec, out); passed += popt_arr5; failed += fopt_arr5;
  final (pnest_opt1, fnest_opt1) = testModel_nest_opt1(vec, out); passed += pnest_opt1; failed += fnest_opt1;
  final (pnest_opt2, fnest_opt2) = testModel_nest_opt2(vec, out); passed += pnest_opt2; failed += fnest_opt2;
  final (pnest_opt3, fnest_opt3) = testModel_nest_opt3(vec, out); passed += pnest_opt3; failed += fnest_opt3;
  final (pnest_opt4, fnest_opt4) = testModel_nest_opt4(vec, out); passed += pnest_opt4; failed += fnest_opt4;
  final (pnest_opt5, fnest_opt5) = testModel_nest_opt5(vec, out); passed += pnest_opt5; failed += fnest_opt5;
  final (pnest_opt_inner1, fnest_opt_inner1) = testModel_nest_opt_inner1(vec, out); passed += pnest_opt_inner1; failed += fnest_opt_inner1;
  final (pnest_opt_inner2, fnest_opt_inner2) = testModel_nest_opt_inner2(vec, out); passed += pnest_opt_inner2; failed += fnest_opt_inner2;
  final (pnest_opt_inner3, fnest_opt_inner3) = testModel_nest_opt_inner3(vec, out); passed += pnest_opt_inner3; failed += fnest_opt_inner3;
  final (pdeep_nest1, fdeep_nest1) = testModel_deep_nest1(vec, out); passed += pdeep_nest1; failed += fdeep_nest1;
  final (pdeep_nest2, fdeep_nest2) = testModel_deep_nest2(vec, out); passed += pdeep_nest2; failed += fdeep_nest2;
  final (pdeep_nest3, fdeep_nest3) = testModel_deep_nest3(vec, out); passed += pdeep_nest3; failed += fdeep_nest3;
  final (pdeep_nest4, fdeep_nest4) = testModel_deep_nest4(vec, out); passed += pdeep_nest4; failed += fdeep_nest4;
  final (pdeep_nest5, fdeep_nest5) = testModel_deep_nest5(vec, out); passed += pdeep_nest5; failed += fdeep_nest5;
  final (pdeep_nest6, fdeep_nest6) = testModel_deep_nest6(vec, out); passed += pdeep_nest6; failed += fdeep_nest6;
  final (pdeep_nest7, fdeep_nest7) = testModel_deep_nest7(vec, out); passed += pdeep_nest7; failed += fdeep_nest7;
  final (ptimestamp_entry, ftimestamp_entry) = testModel_timestamp_entry(vec, out); passed += ptimestamp_entry; failed += ftimestamp_entry;
  final (pconfig_entry, fconfig_entry) = testModel_config_entry(vec, out); passed += pconfig_entry; failed += fconfig_entry;
  return (passed, failed);
}
