// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_edge_empty(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeEmptyCodec;
  try {
    final data = File('$vec/EdgeEmpty.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeEmpty.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeEmpty mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeEmpty.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeEmpty.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeEmpty json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeEmpty.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeEmpty.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeEmpty unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeEmpty.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeEmpty.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeEmpty gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_one_opt(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeOneOptCodec;
  try {
    final data = File('$vec/EdgeOneOpt.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeOneOpt.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeOneOpt mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeOneOpt.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeOneOpt.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeOneOpt json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeOneOpt.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeOneOpt.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeOneOpt unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeOneOpt.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeOneOpt.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeOneOpt gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_big_nums(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeBigNumsCodec;
  try {
    final data = File('$vec/EdgeBigNums.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeBigNums.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBigNums mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBigNums.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeBigNums.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBigNums json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBigNums.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeBigNums.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBigNums unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBigNums.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeBigNums.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBigNums gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_zero_vals(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeZeroValsCodec;
  try {
    final data = File('$vec/EdgeZeroVals.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeZeroVals.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeZeroVals mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeZeroVals.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeZeroVals.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeZeroVals json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeZeroVals.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeZeroVals.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeZeroVals unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeZeroVals.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeZeroVals.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeZeroVals gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_nullable(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeNullableCodec;
  try {
    final data = File('$vec/EdgeNullable.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullable.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullable mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNullable.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullable.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullable json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNullable.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullable.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullable unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNullable.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullable.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullable gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_neg_zero(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeNegZeroCodec;
  try {
    final data = File('$vec/EdgeNegZero.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeNegZero.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNegZero mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNegZero.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeNegZero.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNegZero json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNegZero.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeNegZero.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNegZero unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNegZero.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeNegZero.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNegZero gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_null_byte(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeNullByteCodec;
  try {
    final data = File('$vec/EdgeNullByte.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullByte.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullByte mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNullByte.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullByte.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullByte json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNullByte.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullByte.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullByte unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeNullByte.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeNullByte.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeNullByte gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_boundary(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeBoundaryCodec;
  try {
    final data = File('$vec/EdgeBoundary.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeBoundary.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBoundary mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBoundary.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeBoundary.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBoundary json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBoundary.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeBoundary.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBoundary unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBoundary.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeBoundary.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBoundary gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_str_len(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeStrLenCodec;
  try {
    final data = File('$vec/EdgeStrLen.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeStrLen.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeStrLen mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeStrLen.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeStrLen.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeStrLen json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeStrLen.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeStrLen.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeStrLen unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeStrLen.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeStrLen.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeStrLen gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_bytes_len(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeBytesLenCodec;
  try {
    final data = File('$vec/EdgeBytesLen.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeBytesLen.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBytesLen mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBytesLen.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeBytesLen.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBytesLen json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBytesLen.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeBytesLen.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBytesLen unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeBytesLen.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeBytesLen.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeBytesLen gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_arr_empty(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeArrEmptyCodec;
  try {
    final data = File('$vec/EdgeArrEmpty.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrEmpty.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrEmpty mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeArrEmpty.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrEmpty.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrEmpty json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeArrEmpty.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrEmpty.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrEmpty unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeArrEmpty.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrEmpty.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrEmpty gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_edge_arr_boundary(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = EdgeArrBoundaryCodec;
  try {
    final data = File('$vec/EdgeArrBoundary.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrBoundary.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrBoundary mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeArrBoundary.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrBoundary.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrBoundary json: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeArrBoundary.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrBoundary.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrBoundary unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/EdgeArrBoundary.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/EdgeArrBoundary.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL EdgeArrBoundary gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesEdge(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pedge_empty, fedge_empty) = testModel_edge_empty(vec, out); passed += pedge_empty; failed += fedge_empty;
  final (pedge_one_opt, fedge_one_opt) = testModel_edge_one_opt(vec, out); passed += pedge_one_opt; failed += fedge_one_opt;
  final (pedge_big_nums, fedge_big_nums) = testModel_edge_big_nums(vec, out); passed += pedge_big_nums; failed += fedge_big_nums;
  final (pedge_zero_vals, fedge_zero_vals) = testModel_edge_zero_vals(vec, out); passed += pedge_zero_vals; failed += fedge_zero_vals;
  final (pedge_nullable, fedge_nullable) = testModel_edge_nullable(vec, out); passed += pedge_nullable; failed += fedge_nullable;
  final (pedge_neg_zero, fedge_neg_zero) = testModel_edge_neg_zero(vec, out); passed += pedge_neg_zero; failed += fedge_neg_zero;
  final (pedge_null_byte, fedge_null_byte) = testModel_edge_null_byte(vec, out); passed += pedge_null_byte; failed += fedge_null_byte;
  final (pedge_boundary, fedge_boundary) = testModel_edge_boundary(vec, out); passed += pedge_boundary; failed += fedge_boundary;
  final (pedge_str_len, fedge_str_len) = testModel_edge_str_len(vec, out); passed += pedge_str_len; failed += fedge_str_len;
  final (pedge_bytes_len, fedge_bytes_len) = testModel_edge_bytes_len(vec, out); passed += pedge_bytes_len; failed += fedge_bytes_len;
  final (pedge_arr_empty, fedge_arr_empty) = testModel_edge_arr_empty(vec, out); passed += pedge_arr_empty; failed += fedge_arr_empty;
  final (pedge_arr_boundary, fedge_arr_boundary) = testModel_edge_arr_boundary(vec, out); passed += pedge_arr_boundary; failed += fedge_arr_boundary;
  return (passed, failed);
}
