// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_opt_single_string(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleStringCodec;
  try {
    final data = File('$vec/OptSingleString.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleString.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleString mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleString.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleString.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleString json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleString.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleString.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleString unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleString.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleString.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleString gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleBooleanCodec;
  try {
    final data = File('$vec/OptSingleBoolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBoolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBoolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleBoolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBoolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBoolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleBoolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBoolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBoolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleBoolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBoolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBoolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_int8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleInt8Codec;
  try {
    final data = File('$vec/OptSingleInt8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_int16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleInt16Codec;
  try {
    final data = File('$vec/OptSingleInt16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleInt32Codec;
  try {
    final data = File('$vec/OptSingleInt32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleInt64Codec;
  try {
    final data = File('$vec/OptSingleInt64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleInt64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleInt64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleInt64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_uint8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleUint8Codec;
  try {
    final data = File('$vec/OptSingleUint8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_uint16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleUint16Codec;
  try {
    final data = File('$vec/OptSingleUint16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_uint32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleUint32Codec;
  try {
    final data = File('$vec/OptSingleUint32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleUint64Codec;
  try {
    final data = File('$vec/OptSingleUint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleUint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleUint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleUint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_float32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleFloat32Codec;
  try {
    final data = File('$vec/OptSingleFloat32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleFloat32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleFloat32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleFloat32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleFloat64Codec;
  try {
    final data = File('$vec/OptSingleFloat64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleFloat64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleFloat64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleFloat64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleFloat64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleFloat64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_single_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptSingleBytesCodec;
  try {
    final data = File('$vec/OptSingleBytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleBytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleBytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptSingleBytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptSingleBytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptSingleBytes gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesOpt(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (popt_single_string, fopt_single_string) = testModel_opt_single_string(vec, out); passed += popt_single_string; failed += fopt_single_string;
  final (popt_single_boolean, fopt_single_boolean) = testModel_opt_single_boolean(vec, out); passed += popt_single_boolean; failed += fopt_single_boolean;
  final (popt_single_int8, fopt_single_int8) = testModel_opt_single_int8(vec, out); passed += popt_single_int8; failed += fopt_single_int8;
  final (popt_single_int16, fopt_single_int16) = testModel_opt_single_int16(vec, out); passed += popt_single_int16; failed += fopt_single_int16;
  final (popt_single_int32, fopt_single_int32) = testModel_opt_single_int32(vec, out); passed += popt_single_int32; failed += fopt_single_int32;
  final (popt_single_int64, fopt_single_int64) = testModel_opt_single_int64(vec, out); passed += popt_single_int64; failed += fopt_single_int64;
  final (popt_single_uint8, fopt_single_uint8) = testModel_opt_single_uint8(vec, out); passed += popt_single_uint8; failed += fopt_single_uint8;
  final (popt_single_uint16, fopt_single_uint16) = testModel_opt_single_uint16(vec, out); passed += popt_single_uint16; failed += fopt_single_uint16;
  final (popt_single_uint32, fopt_single_uint32) = testModel_opt_single_uint32(vec, out); passed += popt_single_uint32; failed += fopt_single_uint32;
  final (popt_single_uint64, fopt_single_uint64) = testModel_opt_single_uint64(vec, out); passed += popt_single_uint64; failed += fopt_single_uint64;
  final (popt_single_float32, fopt_single_float32) = testModel_opt_single_float32(vec, out); passed += popt_single_float32; failed += fopt_single_float32;
  final (popt_single_float64, fopt_single_float64) = testModel_opt_single_float64(vec, out); passed += popt_single_float64; failed += fopt_single_float64;
  final (popt_single_bytes, fopt_single_bytes) = testModel_opt_single_bytes(vec, out); passed += popt_single_bytes; failed += fopt_single_bytes;
  return (passed, failed);
}
