// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_arr_string(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrStringCodec;
  try {
    final data = File('$vec/ArrString.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrString.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrString mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrString.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrString.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrString json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrString.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrString.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrString unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrString.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrString.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrString gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_arr_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrInt32Codec;
  try {
    final data = File('$vec/ArrInt32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrInt32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrInt32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrInt32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrInt32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrInt32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrInt32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrInt32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_arr_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrBooleanCodec;
  try {
    final data = File('$vec/ArrBoolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrBoolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBoolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrBoolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrBoolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBoolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrBoolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrBoolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBoolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrBoolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrBoolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBoolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_arr_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrFloat64Codec;
  try {
    final data = File('$vec/ArrFloat64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrFloat64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrFloat64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrFloat64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrFloat64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrFloat64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrFloat64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrFloat64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrFloat64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrFloat64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrFloat64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrFloat64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_arr_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrBytesCodec;
  try {
    final data = File('$vec/ArrBytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrBytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrBytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrBytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrBytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrBytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrBytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrBytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrBytes gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_arr_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrInt64Codec;
  try {
    final data = File('$vec/ArrInt64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrInt64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrInt64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrInt64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrInt64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrInt64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrInt64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrInt64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrInt64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_arr_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ArrUint64Codec;
  try {
    final data = File('$vec/ArrUint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ArrUint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrUint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrUint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrUint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrUint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrUint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ArrUint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrUint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ArrUint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ArrUint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ArrUint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_multi_arr1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MultiArr1Codec;
  try {
    final data = File('$vec/MultiArr1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MultiArr1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MultiArr1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_multi_arr2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MultiArr2Codec;
  try {
    final data = File('$vec/MultiArr2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MultiArr2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MultiArr2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_multi_arr3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MultiArr3Codec;
  try {
    final data = File('$vec/MultiArr3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MultiArr3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MultiArr3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_multi_arr4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MultiArr4Codec;
  try {
    final data = File('$vec/MultiArr4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MultiArr4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MultiArr4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_multi_arr5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MultiArr5Codec;
  try {
    final data = File('$vec/MultiArr5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MultiArr5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MultiArr5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MultiArr5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MultiArr5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MultiArr5 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo1(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo1Codec;
  try {
    final data = File('$vec/OptCombo1.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo1.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo1 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo1.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo1.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo1 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo1.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo1.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo1 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo1.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo1.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo1 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo2(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo2Codec;
  try {
    final data = File('$vec/OptCombo2.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo2.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo2 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo2.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo2.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo2 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo2.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo2.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo2 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo2.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo2.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo2 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo3Codec;
  try {
    final data = File('$vec/OptCombo3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo4(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo4Codec;
  try {
    final data = File('$vec/OptCombo4.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo4.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo4 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo4.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo4.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo4 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo4.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo4.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo4 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo4.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo4.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo4 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo5(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo5Codec;
  try {
    final data = File('$vec/OptCombo5.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo5.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo5 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo5.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo5.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo5 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo5.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo5.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo5 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo5.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo5.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo5 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo6(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo6Codec;
  try {
    final data = File('$vec/OptCombo6.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo6.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo6 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo6.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo6.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo6 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo6.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo6.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo6 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo6.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo6.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo6 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo7(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo7Codec;
  try {
    final data = File('$vec/OptCombo7.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo7.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo7 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo7.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo7.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo7 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo7.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo7.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo7 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo7.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo7.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo7 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo8Codec;
  try {
    final data = File('$vec/OptCombo8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo9(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo9Codec;
  try {
    final data = File('$vec/OptCombo9.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo9.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo9 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo9.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo9.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo9 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo9.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo9.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo9 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo9.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo9.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo9 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_combo10(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptCombo10Codec;
  try {
    final data = File('$vec/OptCombo10.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptCombo10.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo10 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo10.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo10.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo10 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo10.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptCombo10.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo10 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptCombo10.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptCombo10.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptCombo10 gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesArrays(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (parr_string, farr_string) = testModel_arr_string(vec, out); passed += parr_string; failed += farr_string;
  final (parr_int32, farr_int32) = testModel_arr_int32(vec, out); passed += parr_int32; failed += farr_int32;
  final (parr_boolean, farr_boolean) = testModel_arr_boolean(vec, out); passed += parr_boolean; failed += farr_boolean;
  final (parr_float64, farr_float64) = testModel_arr_float64(vec, out); passed += parr_float64; failed += farr_float64;
  final (parr_bytes, farr_bytes) = testModel_arr_bytes(vec, out); passed += parr_bytes; failed += farr_bytes;
  final (parr_int64, farr_int64) = testModel_arr_int64(vec, out); passed += parr_int64; failed += farr_int64;
  final (parr_uint64, farr_uint64) = testModel_arr_uint64(vec, out); passed += parr_uint64; failed += farr_uint64;
  final (pmulti_arr1, fmulti_arr1) = testModel_multi_arr1(vec, out); passed += pmulti_arr1; failed += fmulti_arr1;
  final (pmulti_arr2, fmulti_arr2) = testModel_multi_arr2(vec, out); passed += pmulti_arr2; failed += fmulti_arr2;
  final (pmulti_arr3, fmulti_arr3) = testModel_multi_arr3(vec, out); passed += pmulti_arr3; failed += fmulti_arr3;
  final (pmulti_arr4, fmulti_arr4) = testModel_multi_arr4(vec, out); passed += pmulti_arr4; failed += fmulti_arr4;
  final (pmulti_arr5, fmulti_arr5) = testModel_multi_arr5(vec, out); passed += pmulti_arr5; failed += fmulti_arr5;
  final (popt_combo1, fopt_combo1) = testModel_opt_combo1(vec, out); passed += popt_combo1; failed += fopt_combo1;
  final (popt_combo2, fopt_combo2) = testModel_opt_combo2(vec, out); passed += popt_combo2; failed += fopt_combo2;
  final (popt_combo3, fopt_combo3) = testModel_opt_combo3(vec, out); passed += popt_combo3; failed += fopt_combo3;
  final (popt_combo4, fopt_combo4) = testModel_opt_combo4(vec, out); passed += popt_combo4; failed += fopt_combo4;
  final (popt_combo5, fopt_combo5) = testModel_opt_combo5(vec, out); passed += popt_combo5; failed += fopt_combo5;
  final (popt_combo6, fopt_combo6) = testModel_opt_combo6(vec, out); passed += popt_combo6; failed += fopt_combo6;
  final (popt_combo7, fopt_combo7) = testModel_opt_combo7(vec, out); passed += popt_combo7; failed += fopt_combo7;
  final (popt_combo8, fopt_combo8) = testModel_opt_combo8(vec, out); passed += popt_combo8; failed += fopt_combo8;
  final (popt_combo9, fopt_combo9) = testModel_opt_combo9(vec, out); passed += popt_combo9; failed += fopt_combo9;
  final (popt_combo10, fopt_combo10) = testModel_opt_combo10(vec, out); passed += popt_combo10; failed += fopt_combo10;
  return (passed, failed);
}
