// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_single_string(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleStringCodec;
  try {
    final data = File('$vec/SingleString.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleString.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleString mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleString.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleString.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleString json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleString.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleString.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleString unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleString.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleString.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleString gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_boolean(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleBooleanCodec;
  try {
    final data = File('$vec/SingleBoolean.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleBoolean.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBoolean mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleBoolean.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleBoolean.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBoolean json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleBoolean.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleBoolean.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBoolean unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleBoolean.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleBoolean.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBoolean gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_int8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleInt8Codec;
  try {
    final data = File('$vec/SingleInt8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleInt8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleInt8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_int16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleInt16Codec;
  try {
    final data = File('$vec/SingleInt16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleInt16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleInt16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_int32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleInt32Codec;
  try {
    final data = File('$vec/SingleInt32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleInt32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleInt32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_int64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleInt64Codec;
  try {
    final data = File('$vec/SingleInt64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleInt64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleInt64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleInt64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleInt64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleInt64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_uint8(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleUint8Codec;
  try {
    final data = File('$vec/SingleUint8.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleUint8.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint8 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint8.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint8.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint8 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint8.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint8.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint8 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint8.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleUint8.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint8 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_uint16(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleUint16Codec;
  try {
    final data = File('$vec/SingleUint16.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleUint16.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint16 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint16.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint16.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint16 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint16.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint16.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint16 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint16.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleUint16.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint16 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_uint32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleUint32Codec;
  try {
    final data = File('$vec/SingleUint32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleUint32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleUint32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_uint64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleUint64Codec;
  try {
    final data = File('$vec/SingleUint64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleUint64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleUint64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleUint64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleUint64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleUint64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_float32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleFloat32Codec;
  try {
    final data = File('$vec/SingleFloat32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleFloat32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleFloat32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleFloat32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_float64(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleFloat64Codec;
  try {
    final data = File('$vec/SingleFloat64.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat64.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat64 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleFloat64.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat64.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat64 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleFloat64.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat64.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat64 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleFloat64.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleFloat64.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleFloat64 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_single_bytes(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = SingleBytesCodec;
  try {
    final data = File('$vec/SingleBytes.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/SingleBytes.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBytes mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleBytes.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleBytes.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBytes json: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleBytes.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/SingleBytes.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBytes unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/SingleBytes.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/SingleBytes.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL SingleBytes gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesScalars(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (psingle_string, fsingle_string) = testModel_single_string(vec, out); passed += psingle_string; failed += fsingle_string;
  final (psingle_boolean, fsingle_boolean) = testModel_single_boolean(vec, out); passed += psingle_boolean; failed += fsingle_boolean;
  final (psingle_int8, fsingle_int8) = testModel_single_int8(vec, out); passed += psingle_int8; failed += fsingle_int8;
  final (psingle_int16, fsingle_int16) = testModel_single_int16(vec, out); passed += psingle_int16; failed += fsingle_int16;
  final (psingle_int32, fsingle_int32) = testModel_single_int32(vec, out); passed += psingle_int32; failed += fsingle_int32;
  final (psingle_int64, fsingle_int64) = testModel_single_int64(vec, out); passed += psingle_int64; failed += fsingle_int64;
  final (psingle_uint8, fsingle_uint8) = testModel_single_uint8(vec, out); passed += psingle_uint8; failed += fsingle_uint8;
  final (psingle_uint16, fsingle_uint16) = testModel_single_uint16(vec, out); passed += psingle_uint16; failed += fsingle_uint16;
  final (psingle_uint32, fsingle_uint32) = testModel_single_uint32(vec, out); passed += psingle_uint32; failed += fsingle_uint32;
  final (psingle_uint64, fsingle_uint64) = testModel_single_uint64(vec, out); passed += psingle_uint64; failed += fsingle_uint64;
  final (psingle_float32, fsingle_float32) = testModel_single_float32(vec, out); passed += psingle_float32; failed += fsingle_float32;
  final (psingle_float64, fsingle_float64) = testModel_single_float64(vec, out); passed += psingle_float64; failed += fsingle_float64;
  final (psingle_bytes, fsingle_bytes) = testModel_single_bytes(vec, out); passed += psingle_bytes; failed += fsingle_bytes;
  return (passed, failed);
}
