// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_rec_list(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = RecListCodec;
  try {
    final data = File('$vec/RecList.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/RecList.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecList mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecList.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecList.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecList json: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecList.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecList.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecList unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecList.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/RecList.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecList gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_rec_tree(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = RecTreeCodec;
  try {
    final data = File('$vec/RecTree.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/RecTree.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecTree mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecTree.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecTree.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecTree json: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecTree.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecTree.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecTree unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecTree.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/RecTree.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecTree gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_rec_chain(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = RecChainCodec;
  try {
    final data = File('$vec/RecChain.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/RecChain.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecChain mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecChain.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecChain.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecChain json: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecChain.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecChain.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecChain unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecChain.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/RecChain.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecChain gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_rec_wrap(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = RecWrapCodec;
  try {
    final data = File('$vec/RecWrap.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/RecWrap.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWrap mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecWrap.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecWrap.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWrap json: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecWrap.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecWrap.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWrap unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecWrap.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/RecWrap.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWrap gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_rec_wide(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = RecWideCodec;
  try {
    final data = File('$vec/RecWide.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/RecWide.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWide mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecWide.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecWide.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWide json: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecWide.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/RecWide.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWide unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/RecWide.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/RecWide.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL RecWide gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesRecursive(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (prec_list, frec_list) = testModel_rec_list(vec, out); passed += prec_list; failed += frec_list;
  final (prec_tree, frec_tree) = testModel_rec_tree(vec, out); passed += prec_tree; failed += frec_tree;
  final (prec_chain, frec_chain) = testModel_rec_chain(vec, out); passed += prec_chain; failed += frec_chain;
  final (prec_wrap, frec_wrap) = testModel_rec_wrap(vec, out); passed += prec_wrap; failed += frec_wrap;
  final (prec_wide, frec_wide) = testModel_rec_wide(vec, out); passed += prec_wide; failed += frec_wide;
  return (passed, failed);
}
