// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_nest_inner(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestInnerCodec;
  try {
    final data = File('$vec/NestInner.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestInner.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestInner mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestInner.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestInner.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestInner json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestInner.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestInner.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestInner unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestInner.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestInner.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestInner gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_coord(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestCoordCodec;
  try {
    final data = File('$vec/NestCoord.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestCoord.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestCoord mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestCoord.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestCoord.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestCoord json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestCoord.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestCoord.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestCoord unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestCoord.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestCoord.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestCoord gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_id_val(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestIdValCodec;
  try {
    final data = File('$vec/NestIdVal.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestIdVal.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestIdVal mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestIdVal.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestIdVal.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestIdVal json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestIdVal.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestIdVal.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestIdVal unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestIdVal.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestIdVal.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestIdVal gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_label(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestLabelCodec;
  try {
    final data = File('$vec/NestLabel.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestLabel.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestLabel mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestLabel.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestLabel.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestLabel json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestLabel.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestLabel.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestLabel unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestLabel.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestLabel.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestLabel gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_money(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestMoneyCodec;
  try {
    final data = File('$vec/NestMoney.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestMoney.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestMoney mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestMoney.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestMoney.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestMoney json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestMoney.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestMoney.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestMoney unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestMoney.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestMoney.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestMoney gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_range32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestRange32Codec;
  try {
    final data = File('$vec/NestRange32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestRange32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestRange32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestRange32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestRange32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestRange32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestRange32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestRange32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestRange32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestRange32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestRange32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestRange32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_addr(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestAddrCodec;
  try {
    final data = File('$vec/NestAddr.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestAddr.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestAddr mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestAddr.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestAddr.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestAddr json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestAddr.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestAddr.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestAddr unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestAddr.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestAddr.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestAddr gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nest_point3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestPoint3Codec;
  try {
    final data = File('$vec/NestPoint3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestPoint3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestPoint3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestPoint3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestPoint3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestPoint3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestPoint3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestPoint3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestPoint3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestPoint3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestPoint3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestPoint3 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_inner(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestInnerCodec;
  try {
    final data = File('$vec/OptNestInner.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestInner.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestInner mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestInner.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestInner.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestInner json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestInner.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestInner.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestInner unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestInner.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestInner.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestInner gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_coord(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestCoordCodec;
  try {
    final data = File('$vec/OptNestCoord.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestCoord.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestCoord mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestCoord.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestCoord.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestCoord json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestCoord.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestCoord.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestCoord unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestCoord.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestCoord.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestCoord gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_id_val(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestIdValCodec;
  try {
    final data = File('$vec/OptNestIdVal.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestIdVal.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestIdVal mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestIdVal.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestIdVal.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestIdVal json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestIdVal.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestIdVal.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestIdVal unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestIdVal.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestIdVal.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestIdVal gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_label(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestLabelCodec;
  try {
    final data = File('$vec/OptNestLabel.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestLabel.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestLabel mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestLabel.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestLabel.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestLabel json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestLabel.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestLabel.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestLabel unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestLabel.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestLabel.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestLabel gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_money(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestMoneyCodec;
  try {
    final data = File('$vec/OptNestMoney.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestMoney.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestMoney mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestMoney.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestMoney.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestMoney json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestMoney.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestMoney.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestMoney unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestMoney.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestMoney.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestMoney gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_range32(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestRange32Codec;
  try {
    final data = File('$vec/OptNestRange32.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestRange32.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestRange32 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestRange32.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestRange32.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestRange32 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestRange32.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestRange32.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestRange32 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestRange32.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestRange32.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestRange32 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_addr(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestAddrCodec;
  try {
    final data = File('$vec/OptNestAddr.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestAddr.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestAddr mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestAddr.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestAddr.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestAddr json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestAddr.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestAddr.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestAddr unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestAddr.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestAddr.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestAddr gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_nest_point3(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptNestPoint3Codec;
  try {
    final data = File('$vec/OptNestPoint3.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptNestPoint3.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestPoint3 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestPoint3.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestPoint3.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestPoint3 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestPoint3.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptNestPoint3.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestPoint3 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptNestPoint3.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptNestPoint3.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptNestPoint3 gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesNests(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pnest_inner, fnest_inner) = testModel_nest_inner(vec, out); passed += pnest_inner; failed += fnest_inner;
  final (pnest_coord, fnest_coord) = testModel_nest_coord(vec, out); passed += pnest_coord; failed += fnest_coord;
  final (pnest_id_val, fnest_id_val) = testModel_nest_id_val(vec, out); passed += pnest_id_val; failed += fnest_id_val;
  final (pnest_label, fnest_label) = testModel_nest_label(vec, out); passed += pnest_label; failed += fnest_label;
  final (pnest_money, fnest_money) = testModel_nest_money(vec, out); passed += pnest_money; failed += fnest_money;
  final (pnest_range32, fnest_range32) = testModel_nest_range32(vec, out); passed += pnest_range32; failed += fnest_range32;
  final (pnest_addr, fnest_addr) = testModel_nest_addr(vec, out); passed += pnest_addr; failed += fnest_addr;
  final (pnest_point3, fnest_point3) = testModel_nest_point3(vec, out); passed += pnest_point3; failed += fnest_point3;
  final (popt_nest_inner, fopt_nest_inner) = testModel_opt_nest_inner(vec, out); passed += popt_nest_inner; failed += fopt_nest_inner;
  final (popt_nest_coord, fopt_nest_coord) = testModel_opt_nest_coord(vec, out); passed += popt_nest_coord; failed += fopt_nest_coord;
  final (popt_nest_id_val, fopt_nest_id_val) = testModel_opt_nest_id_val(vec, out); passed += popt_nest_id_val; failed += fopt_nest_id_val;
  final (popt_nest_label, fopt_nest_label) = testModel_opt_nest_label(vec, out); passed += popt_nest_label; failed += fopt_nest_label;
  final (popt_nest_money, fopt_nest_money) = testModel_opt_nest_money(vec, out); passed += popt_nest_money; failed += fopt_nest_money;
  final (popt_nest_range32, fopt_nest_range32) = testModel_opt_nest_range32(vec, out); passed += popt_nest_range32; failed += fopt_nest_range32;
  final (popt_nest_addr, fopt_nest_addr) = testModel_opt_nest_addr(vec, out); passed += popt_nest_addr; failed += fopt_nest_addr;
  final (popt_nest_point3, fopt_nest_point3) = testModel_opt_nest_point3(vec, out); passed += popt_nest_point3; failed += fopt_nest_point3;
  return (passed, failed);
}
