// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_five01(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five01Codec;
  try {
    final data = File('$vec/Five01.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five01.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five01 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five01.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five01.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five01 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five01.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five01.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five01 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five01.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five01.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five01 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five02(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five02Codec;
  try {
    final data = File('$vec/Five02.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five02.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five02 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five02.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five02.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five02 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five02.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five02.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five02 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five02.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five02.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five02 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five03(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five03Codec;
  try {
    final data = File('$vec/Five03.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five03.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five03 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five03.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five03.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five03 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five03.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five03.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five03 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five03.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five03.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five03 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five04(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five04Codec;
  try {
    final data = File('$vec/Five04.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five04.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five04 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five04.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five04.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five04 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five04.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five04.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five04 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five04.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five04.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five04 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five05(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five05Codec;
  try {
    final data = File('$vec/Five05.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five05.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five05 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five05.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five05.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five05 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five05.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five05.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five05 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five05.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five05.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five05 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five06(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five06Codec;
  try {
    final data = File('$vec/Five06.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five06.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five06 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five06.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five06.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five06 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five06.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five06.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five06 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five06.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five06.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five06 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five07(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five07Codec;
  try {
    final data = File('$vec/Five07.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five07.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five07 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five07.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five07.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five07 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five07.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five07.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five07 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five07.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five07.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five07 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five08(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five08Codec;
  try {
    final data = File('$vec/Five08.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five08.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five08 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five08.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five08.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five08 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five08.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five08.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five08 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five08.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five08.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five08 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five09(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five09Codec;
  try {
    final data = File('$vec/Five09.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five09.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five09 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five09.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five09.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five09 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five09.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five09.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five09 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five09.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five09.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five09 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_five10(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Five10Codec;
  try {
    final data = File('$vec/Five10.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Five10.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five10 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five10.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five10.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five10 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five10.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Five10.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five10 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Five10.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Five10.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Five10 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ten01(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Ten01Codec;
  try {
    final data = File('$vec/Ten01.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ten01.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten01 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten01.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten01.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten01 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten01.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten01.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten01 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten01.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ten01.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten01 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ten02(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Ten02Codec;
  try {
    final data = File('$vec/Ten02.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ten02.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten02 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten02.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten02.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten02 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten02.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten02.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten02 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten02.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ten02.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten02 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ten03(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Ten03Codec;
  try {
    final data = File('$vec/Ten03.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ten03.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten03 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten03.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten03.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten03 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten03.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten03.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten03 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten03.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ten03.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten03 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ten04(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Ten04Codec;
  try {
    final data = File('$vec/Ten04.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ten04.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten04 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten04.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten04.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten04 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten04.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten04.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten04 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten04.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ten04.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten04 gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ten05(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = Ten05Codec;
  try {
    final data = File('$vec/Ten05.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ten05.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten05 mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten05.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten05.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten05 json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten05.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ten05.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten05 unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ten05.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ten05.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ten05 gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesMany(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pfive01, ffive01) = testModel_five01(vec, out); passed += pfive01; failed += ffive01;
  final (pfive02, ffive02) = testModel_five02(vec, out); passed += pfive02; failed += ffive02;
  final (pfive03, ffive03) = testModel_five03(vec, out); passed += pfive03; failed += ffive03;
  final (pfive04, ffive04) = testModel_five04(vec, out); passed += pfive04; failed += ffive04;
  final (pfive05, ffive05) = testModel_five05(vec, out); passed += pfive05; failed += ffive05;
  final (pfive06, ffive06) = testModel_five06(vec, out); passed += pfive06; failed += ffive06;
  final (pfive07, ffive07) = testModel_five07(vec, out); passed += pfive07; failed += ffive07;
  final (pfive08, ffive08) = testModel_five08(vec, out); passed += pfive08; failed += ffive08;
  final (pfive09, ffive09) = testModel_five09(vec, out); passed += pfive09; failed += ffive09;
  final (pfive10, ffive10) = testModel_five10(vec, out); passed += pfive10; failed += ffive10;
  final (pten01, ften01) = testModel_ten01(vec, out); passed += pten01; failed += ften01;
  final (pten02, ften02) = testModel_ten02(vec, out); passed += pten02; failed += ften02;
  final (pten03, ften03) = testModel_ten03(vec, out); passed += pten03; failed += ften03;
  final (pten04, ften04) = testModel_ten04(vec, out); passed += pten04; failed += ften04;
  final (pten05, ften05) = testModel_ten05(vec, out); passed += pten05; failed += ften05;
  return (passed, failed);
}
