// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_nested_simple(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestedSimpleCodec;
  try {
    final data = File('$vec/NestedSimple.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestedSimple.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedSimple mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedSimple.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestedSimple.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedSimple json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedSimple.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestedSimple.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedSimple unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedSimple.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestedSimple.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedSimple gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runAllTypesNested(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pnested_simple, fnested_simple) = testModel_nested_simple(vec, out); passed += pnested_simple; failed += fnested_simple;
  return (passed, failed);
}
