// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';


(int, int) testModel_shape_circle(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ShapeCodec;
  try {
    final data = File('$vec/Shape_circle.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Shape_circle.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_circle mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Shape_circle.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Shape_circle.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_circle json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Shape_circle.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Shape_circle.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_circle unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Shape_circle.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Shape_circle.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_circle gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_shape_rect(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ShapeCodec;
  try {
    final data = File('$vec/Shape_rect.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Shape_rect.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_rect mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Shape_rect.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Shape_rect.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_rect json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Shape_rect.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Shape_rect.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_rect unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Shape_rect.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Shape_rect.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Shape_rect gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ident_name(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = IdentCodec;
  try {
    final data = File('$vec/Ident_name.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ident_name.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_name mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ident_name.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ident_name.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_name json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ident_name.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ident_name.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_name unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ident_name.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ident_name.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_name gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_ident_number(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = IdentCodec;
  try {
    final data = File('$vec/Ident_number.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Ident_number.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_number mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ident_number.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ident_number.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_number json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ident_number.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Ident_number.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_number unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Ident_number.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Ident_number.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Ident_number gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_result_msg_ok(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ResultMsgCodec;
  try {
    final data = File('$vec/ResultMsg_ok.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_ok.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_ok mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ResultMsg_ok.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_ok.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_ok json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ResultMsg_ok.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_ok.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_ok unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ResultMsg_ok.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_ok.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_ok gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_result_msg_err(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ResultMsgCodec;
  try {
    final data = File('$vec/ResultMsg_err.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_err.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_err mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ResultMsg_err.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_err.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_err json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ResultMsg_err.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_err.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_err unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ResultMsg_err.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ResultMsg_err.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ResultMsg_err gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_tagged_tag(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = TaggedCodec;
  try {
    final data = File('$vec/Tagged_tag.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Tagged_tag.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_tag mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_tag.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Tagged_tag.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_tag json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_tag.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Tagged_tag.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_tag unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_tag.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Tagged_tag.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_tag gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_tagged_score(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = TaggedCodec;
  try {
    final data = File('$vec/Tagged_score.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Tagged_score.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_score mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_score.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Tagged_score.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_score json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_score.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Tagged_score.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_score unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_score.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Tagged_score.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_score gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_tagged_active(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = TaggedCodec;
  try {
    final data = File('$vec/Tagged_active.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/Tagged_active.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_active mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_active.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Tagged_active.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_active json: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_active.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/Tagged_active.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_active unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/Tagged_active.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/Tagged_active.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL Tagged_active gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_union_holder_shape(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptUnionHolderCodec;
  try {
    final data = File('$vec/OptUnionHolder_shape.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_shape.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_shape mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionHolder_shape.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_shape.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_shape json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionHolder_shape.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_shape.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_shape unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionHolder_shape.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_shape.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_shape gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_opt_union_holder_id(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = OptUnionHolderCodec;
  try {
    final data = File('$vec/OptUnionHolder_id.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_id.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_id mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionHolder_id.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_id.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_id json: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionHolder_id.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_id.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_id unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/OptUnionHolder_id.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/OptUnionHolder_id.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL OptUnionHolder_id gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mixed_union_point(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MixedUnionCodec;
  try {
    final data = File('$vec/MixedUnion_point.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_point.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_point mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_point.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_point.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_point json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_point.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_point.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_point unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_point.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_point.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_point gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mixed_union_label(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MixedUnionCodec;
  try {
    final data = File('$vec/MixedUnion_label.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_label.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_label mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_label.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_label.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_label json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_label.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_label.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_label unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_label.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_label.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_label gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_mixed_union_count(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = MixedUnionCodec;
  try {
    final data = File('$vec/MixedUnion_count.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_count.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_count mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_count.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_count.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_count json: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_count.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_count.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_count unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/MixedUnion_count.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/MixedUnion_count.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL MixedUnion_count gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nested_union_result(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestedUnionCodec;
  try {
    final data = File('$vec/NestedUnion_result.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_result.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_result mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedUnion_result.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_result.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_result json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedUnion_result.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_result.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_result unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedUnion_result.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_result.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_result gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_nested_union_shape(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = NestedUnionCodec;
  try {
    final data = File('$vec/NestedUnion_shape.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_shape.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_shape mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedUnion_shape.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_shape.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_shape json: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedUnion_shape.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_shape.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_shape unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/NestedUnion_shape.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/NestedUnion_shape.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL NestedUnion_shape gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_scalar_union_s(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ScalarUnionCodec;
  try {
    final data = File('$vec/ScalarUnion_s.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_s.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_s mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_s.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_s.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_s json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_s.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_s.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_s unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_s.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_s.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_s gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_scalar_union_i(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ScalarUnionCodec;
  try {
    final data = File('$vec/ScalarUnion_i.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_i.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_i mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_i.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_i.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_i json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_i.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_i.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_i unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_i.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_i.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_i gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_scalar_union_f(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ScalarUnionCodec;
  try {
    final data = File('$vec/ScalarUnion_f.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_f.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_f mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_f.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_f.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_f json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_f.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_f.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_f unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_f.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_f.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_f gron: $e');
    failed++;
  }
  return (passed, failed);
}

(int, int) testModel_scalar_union_b(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ScalarUnionCodec;
  try {
    final data = File('$vec/ScalarUnion_b.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_b.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_b mp: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_b.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_b.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_b json: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_b.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_b.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_b unformatted: $e');
    failed++;
  }
  try {
    final data = File('$vec/ScalarUnion_b.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('$out/ScalarUnion_b.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ScalarUnion_b gron: $e');
    failed++;
  }
  return (passed, failed);
}
(int, int) runModels(String vec, String out) {
  int passed = 0, failed = 0;

  // Object tests
  final (pshape_circle, fshape_circle) = testModel_shape_circle(vec, out); passed += pshape_circle; failed += fshape_circle;
  final (pshape_rect, fshape_rect) = testModel_shape_rect(vec, out); passed += pshape_rect; failed += fshape_rect;
  final (pident_name, fident_name) = testModel_ident_name(vec, out); passed += pident_name; failed += fident_name;
  final (pident_number, fident_number) = testModel_ident_number(vec, out); passed += pident_number; failed += fident_number;
  final (presult_msg_ok, fresult_msg_ok) = testModel_result_msg_ok(vec, out); passed += presult_msg_ok; failed += fresult_msg_ok;
  final (presult_msg_err, fresult_msg_err) = testModel_result_msg_err(vec, out); passed += presult_msg_err; failed += fresult_msg_err;
  final (ptagged_tag, ftagged_tag) = testModel_tagged_tag(vec, out); passed += ptagged_tag; failed += ftagged_tag;
  final (ptagged_score, ftagged_score) = testModel_tagged_score(vec, out); passed += ptagged_score; failed += ftagged_score;
  final (ptagged_active, ftagged_active) = testModel_tagged_active(vec, out); passed += ptagged_active; failed += ftagged_active;
  final (popt_union_holder_shape, fopt_union_holder_shape) = testModel_opt_union_holder_shape(vec, out); passed += popt_union_holder_shape; failed += fopt_union_holder_shape;
  final (popt_union_holder_id, fopt_union_holder_id) = testModel_opt_union_holder_id(vec, out); passed += popt_union_holder_id; failed += fopt_union_holder_id;
  final (pmixed_union_point, fmixed_union_point) = testModel_mixed_union_point(vec, out); passed += pmixed_union_point; failed += fmixed_union_point;
  final (pmixed_union_label, fmixed_union_label) = testModel_mixed_union_label(vec, out); passed += pmixed_union_label; failed += fmixed_union_label;
  final (pmixed_union_count, fmixed_union_count) = testModel_mixed_union_count(vec, out); passed += pmixed_union_count; failed += fmixed_union_count;
  final (pnested_union_result, fnested_union_result) = testModel_nested_union_result(vec, out); passed += pnested_union_result; failed += fnested_union_result;
  final (pnested_union_shape, fnested_union_shape) = testModel_nested_union_shape(vec, out); passed += pnested_union_shape; failed += fnested_union_shape;
  final (pscalar_union_s, fscalar_union_s) = testModel_scalar_union_s(vec, out); passed += pscalar_union_s; failed += fscalar_union_s;
  final (pscalar_union_i, fscalar_union_i) = testModel_scalar_union_i(vec, out); passed += pscalar_union_i; failed += fscalar_union_i;
  final (pscalar_union_f, fscalar_union_f) = testModel_scalar_union_f(vec, out); passed += pscalar_union_f; failed += fscalar_union_f;
  final (pscalar_union_b, fscalar_union_b) = testModel_scalar_union_b(vec, out); passed += pscalar_union_b; failed += fscalar_union_b;
  return (passed, failed);
}
