import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dir = path.dirname(fileURLToPath(import.meta.url));
const VEC_DIR = process.env.VEC_DIR || path.join(__dir, ".tests-cache", "vectors");

const manifestPath = path.join(VEC_DIR, "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));

const models = [...(manifest.testModels || []), ...(manifest.testUnions || [])];
const scalars = manifest.scalars;
const modelNamespaces = manifest.modelNamespaces || {};
const testUnions = new Set(manifest.testUnions || []);
function isUnionTest(name) { return testUnions.has(name); }
function unionNameOf(testName) { return testName.replace(/_[^_]+$/, ''); }

function readMethod(type) {
  const map = {
    "int32": "readInt32", "int64": "readInt64",
    "uint32": "readUint32", "uint64": "readUint64",
    "float32": "readFloat32", "float64": "readFloat64",
    "string": "readString", "bytes": "readBytes", "bool": "readBool",
  };
  return map[type] || "readInt32";
}

function writeMethod(type) {
  const map = {
    "int32": "writeInt32", "int64": "writeInt64",
    "uint32": "writeUint32", "uint64": "writeUint64",
    "float32": "writeFloat32", "float64": "writeFloat64",
    "string": "writeString", "bytes": "writeBytes", "bool": "writeBool",
  };
  return map[type] || "writeInt32";
}

function toSnakeCase(name) {
  let s = name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  return s.replace(/\./g, '_').replace(/-/g, '_');
}

function scalarFunc(name, info) {
  const snake = toSnakeCase(name);
  return `
(int, int) testScalar_${snake}(String vec, String out) {
  try {
    final data = File('\$vec/scalars/${name}.mp').readAsBytesSync();
    final r = MsgPackReader(data);
    final val = r.${readMethod(info.type)}();
    final w = MsgPackWriter();
    w.${writeMethod(info.type)}(val);
    File('\$out/scalars/${name}.mp').writeAsBytesSync(w.toBytes());
    return (1, 0);
  } catch (e) {
    print('FAIL ${name} mp: \$e');
    return (0, 1);
  }
}`;
}

function scalarCall(name) {
  const snake = toSnakeCase(name);
  return `  final (p${snake}, f${snake}) = testScalar_${snake}(vec, out); passed += p${snake}; failed += f${snake};\n`;
}

function modelFunc(model) {
  const snake = toSnakeCase(model);
  const codecName = isUnionTest(model) ? unionNameOf(model) : model;
  return `
(int, int) testModel_${snake}(String vec, String out) {
  int passed = 0, failed = 0;
  final codec = ${codecName}Codec;
  try {
    final data = File('\$vec/${model}.msgpack').readAsBytesSync();
    final obj = codec.decode(MsgPackReader(data));
    final w = MsgPackWriter();
    codec.encode(w, obj);
    File('\$out/${model}.msgpack').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ${model} mp: \$e');
    failed++;
  }
  try {
    final data = File('\$vec/${model}.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('\$out/${model}.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ${model} json: \$e');
    failed++;
  }
  try {
    final data = File('\$vec/${model}.unformatted.json').readAsBytesSync();
    final obj = codec.decode(JsonReader(data));
    final w = JsonWriter();
    codec.encode(w, obj);
    File('\$out/${model}.unformatted.json').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ${model} unformatted: \$e');
    failed++;
  }
  try {
    final data = File('\$vec/${model}.gron').readAsBytesSync();
    final obj = codec.decode(GronReader(data));
    final w = GronWriter();
    codec.encode(w, obj);
    File('\$out/${model}.gron').writeAsBytesSync(w.toBytes());
    passed++;
  } catch (e) {
    print('FAIL ${model} gron: \$e');
    failed++;
  }
  return (passed, failed);
}`;
}

function modelCall(model) {
  const snake = toSnakeCase(model);
  return `  final (p${snake}, f${snake}) = testModel_${snake}(vec, out); passed += p${snake}; failed += f${snake};\n`;
}

// Group models by namespace
const groups = {};
for (const model of models) {
  const nsStr = modelNamespaces[model] || ""; const ns = nsStr ? nsStr.split(".") : [];
  const key = ns.length > 0 ? ns.join("_") : "_root";
  if (!groups[key]) groups[key] = [];
  groups[key].push(model);
}

function nsFuncName(key) {
  if (key === "_root") return "runModels";
  return "run" + key.split("_").map(s => s[0].toUpperCase() + s.slice(1)).join("");
}

function nsFileName(key) {
  const n = key === "_root" ? "models" : key;
  return "test_" + n + ".dart";
}

const outDir = path.join(__dir, "emit");
fs.mkdirSync(outDir, { recursive: true });

const preamble = `// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';
`;

const groupKeys = Object.keys(groups);
const groupInfo = [];

// Scalar-only file
if (Object.keys(scalars).length > 0) {
  let scalarBody = preamble + "\n";
  for (const [name, info] of Object.entries(scalars)) {
    scalarBody += scalarFunc(name, info) + "\n";
  }
  scalarBody += `(int, int) runScalars(String vec, String out) {\n`;
  scalarBody += `  int passed = 0, failed = 0;\n`;
  scalarBody += `\n  // Scalar tests\n`;
  for (const [name] of Object.entries(scalars)) {
    scalarBody += scalarCall(name);
  }
  scalarBody += `  return (passed, failed);\n`;
  scalarBody += `}\n`;
  const scalarFile = "test_scalars.dart";
  fs.writeFileSync(path.join(outDir, scalarFile), scalarBody);
  groupInfo.push({ key: "_scalars", funcName: "runScalars", fileName: scalarFile });
  console.log(`Generated emit/${scalarFile} with ${Object.keys(scalars).length} scalars`);
}

for (const key of groupKeys) {
  const funcName = nsFuncName(key);
  const fileName = nsFileName(key);
  groupInfo.push({ key, funcName, fileName });
  const mods = groups[key];

  let body = preamble + "\n";

  for (const model of mods) {
    body += modelFunc(model) + "\n";
  }

  body += `(int, int) ${funcName}(String vec, String out) {\n`;
  body += `  int passed = 0, failed = 0;\n`;

  if (mods.length > 0) {
    body += `\n  // Object tests\n`;
    for (const model of mods) {
      body += modelCall(model);
    }
  }

  body += `  return (passed, failed);\n`;
  body += `}\n`;

  const filePath = path.join(outDir, fileName);
  fs.writeFileSync(filePath, body);
  console.log(`Generated emit/${fileName} with ${mods.length} models`);
}

// Write main.dart
let mainSrc = `// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory, Platform, exit;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';

`;

for (const gi of groupInfo) {
  mainSrc += `import '${gi.fileName}';\n`;
}

mainSrc += `
void main() {
  final vec = Platform.environment['VEC_DIR']!;
  final out = Platform.environment['OUT_DIR']!;
  Directory(out).createSync(recursive: true);
  Directory('\$out/scalars').createSync(recursive: true);

  int passed = 0, failed = 0;

`;

for (const gi of groupInfo) {
  mainSrc += `  final (p${gi.funcName}, f${gi.funcName}) = ${gi.funcName}(vec, out); passed += p${gi.funcName}; failed += f${gi.funcName};\n`;
}

mainSrc += `
  print('emit-dart: \$passed passed, \$failed failed');
  if (failed > 0) exit(1);
}
`;

fs.writeFileSync(path.join(outDir, "main.dart"), mainSrc);
console.log("Generated emit/main.dart");
